spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info
