spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/rivoo/protocol/openid-connect/certs

rivoo:
  security:
    internal-service-key: rivoo-dev-internal-key-2026
  services:
    salon-service:
      url: http://localhost:8082
    auth-service:
      url: http://localhost:8081
    appointment-service:
      url: http://localhost:8085
    billing-service:
      url: http://localhost:8087
