spring:
  application:
    name: admin-service
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
      - com.rivoo.common.tenant.TenantAutoConfiguration

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info
